name: SonarCloud Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required to get full git history for SonarCloud analysis
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version here
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have requirements
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic, no need to set in secrets
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Needs to be set in repo secrets
