name: SonarCloud Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud to get full commit history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Install test coverage tools if needed

      - name: Run tests with coverage (optional)
        run: |
          pytest --cov=./ --cov-report=xml  # Generates coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # From SonarCloud
        with:
          projectKey: Credit_Risk_Analysis    # Replace with your key
          organization: AashikaShravani     # Replace with your org
          # Optional args (uncomment if needed):
          # args: >
          #   -Dsonar.python.coverage.reportPaths=coverage.xml
          #   -Dsonar.sources=.
          #   -Dsonar.language=py
