name: Python CI with Teams Alert

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # If pytest is not in requirements.txt

      - name: Run tests
        run: pytest

  notify-teams:
    needs: test
    if: failure()  # Only run if the `test` job fails
    runs-on: ubuntu-latest
    steps:
      - name: Send failure alert to Teams
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TEAMS_WEBHOOK_ID }}  # Replace with a Teams-compatible webhook
          message: |
            ❌ **Python Test Failed**  
            Repository: ${{ github.repository }}  
            Workflow: ${{ github.workflow }}  
            Commit: ${{ github.sha }}  
            View logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
