name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'  # Daily scan

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for GitHub Advanced Security

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Scan repository files (SAST)
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'table'
          exit-code: '1'
          output: 'trivy-results-fs.txt'

      # Scan Python dependencies (if requirements.txt exists)
      - name: Run Trivy dependency scan
        if: exists('requirements.txt')
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'dep'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results-dep.sarif'

      # Upload results to GitHub Security tab (SARIF format)
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-dep.sarif'

      # Print filesystem scan results (optional)
      - name: Show filesystem scan results
        run: |
          cat trivy-results-fs.txt
